#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""theorycat — compact CLI over verification/theory_graph.json.

The graph is GENERATED by verification/build_theory_graph.py from the
status ledger, script registry, docs map, frozen predictions, evidence
scorecard, theory contracts and the RH semantic catalog.  stdlib only.
Lines clip at 120 chars unless --json.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
from collections import Counter, defaultdict

VERIF_DIR = os.path.dirname(os.path.abspath(__file__))
GRAPH_PATH = os.path.join(VERIF_DIR, "theory_graph.json")
LINE_WIDTH = 120
ROUND_TOKEN_RE = re.compile(r"r(\d+)", re.I)


def sha256_file(path):
    import hashlib
    h = hashlib.sha256()
    try:
        with open(path, "rb") as f:
            for chunk in iter(lambda: f.read(65536), b""):
                h.update(chunk)
    except OSError:
        return None
    return h.hexdigest()


def script_hash_status(g, script_nid):
    """Compare the graph's script_sha256 with the file on disk."""
    a = g.node(script_nid)["attrs"]
    want = a.get("script_sha256")
    path = os.path.join(VERIF_DIR, script_nid.split(":", 1)[1] + ".py")
    if not os.path.isfile(path):
        return "FEHLT"
    if not want:
        return "ohne Hash"
    return "aktuell" if sha256_file(path) == want else "GEÄNDERT"


def clip(text, width=LINE_WIDTH):
    text = " ".join(str(text if text is not None else "").split())
    if len(text) <= width:
        return text
    return text[: width - 3] + "..."


def load_graph():
    if not os.path.isfile(GRAPH_PATH):
        sys.stderr.write(
            "theory graph missing: run: python verification/build_theory_graph.py\n"
        )
        sys.exit(2)
    with open(GRAPH_PATH, "r", encoding="utf-8") as fh:
        return json.load(fh)


def maybe_rebuild(no_rebuild=False):
    """Lazy staleness gate: same source-hash logic as --check; on drift
    rebuild once (~2 s) with a stderr note.  --no-rebuild disables."""
    if no_rebuild:
        return
    try:
        sys.path.insert(0, VERIF_DIR)
        import build_theory_graph as btg
    except Exception:
        return
    try:
        with open(GRAPH_PATH, "r", encoding="utf-8") as fh:
            graph = json.load(fh)
    except (OSError, json.JSONDecodeError):
        return
    try:
        stale = btg.stale_sources(graph)
    except Exception:
        return
    if not stale:
        return
    sys.stderr.write("[theorycat] graph rebuilt (stale)\n")
    subprocess.run(
        [sys.executable, os.path.join(VERIF_DIR, "build_theory_graph.py")],
        check=False,
    )


def emit_json(obj):
    sys.stdout.write(
        json.dumps(obj, indent=2, sort_keys=True, ensure_ascii=False) + "\n"
    )


class Graph:
    def __init__(self, payload):
        self.meta = payload.get("meta") or {}
        self.nodes = payload.get("nodes") or []
        self.edges = payload.get("edges") or []
        self.by_id = {n["id"]: n for n in self.nodes}
        self.out_edges = defaultdict(list)
        self.in_edges = defaultdict(list)
        for e in self.edges:
            self.out_edges[e["src"]].append(e)
            self.in_edges[e["dst"]].append(e)

    def node(self, nid):
        return self.by_id.get(nid)


def as_claim_id(graph, arg):
    """Accept 'EM.FP.01' or 'claim:EM.FP.01'."""
    if arg in graph.by_id:
        return arg
    pref = "claim:" + arg
    if pref in graph.by_id:
        return pref
    return None


def fmt_date(raw):
    raw = raw or ""
    if len(raw) == 8 and raw.isdigit():
        return f"{raw[:4]}-{raw[4:6]}-{raw[6:]}"
    return raw or "-"


def recency_key(kind, node):
    """contracts: YYYYMMDD int; rh: first round number; else 0."""
    a = node["attrs"]
    if kind == "contract":
        try:
            return int(a.get("date") or 0)
        except (TypeError, ValueError):
            return 0
    if kind == "rh":
        m = ROUND_TOKEN_RE.search(a.get("round") or "")
        return int(m.group(1)) if m else 0
    return 0


# --------------------------------------------------------------------------
# subcommands
# --------------------------------------------------------------------------

def cmd_stats(g: Graph, as_json):
    counts = g.meta.get("counts") or {}
    coverage = g.meta.get("coverage") or {}
    verdict_dist = Counter(
        n["attrs"].get("verdict_class")
        for n in g.nodes if n["type"] == "contract"
    )
    outcome_dist = Counter(
        n["attrs"].get("outcome") for n in g.nodes if n["type"] == "rh"
    )
    sc_dist = Counter(
        n["attrs"].get("status") for n in g.nodes if n["type"] == "scorecard"
    )
    exp_dist = Counter(
        n["attrs"].get("kind") for n in g.nodes if n["type"] == "experiment"
    )
    marker_dist = Counter()
    for n in g.nodes:
        if n["type"] == "claim":
            marker_dist.update(n["attrs"].get("markers") or [])
    payload = {
        "counts": counts,
        "coverage": coverage,
        "contract_verdict_class": dict(verdict_dist.most_common()),
        "rh_outcome": dict(outcome_dist.most_common()),
        "scorecard_status": dict(sc_dist.most_common()),
        "experiment_kind": dict(exp_dist.most_common()),
        "claim_markers": dict(marker_dist.most_common()),
        "generated": g.meta.get("generated"),
    }
    if as_json:
        emit_json(payload)
        return 0
    sys.stdout.write(
        clip("nodes=%d edges=%d  contracts=%d/%d with verdict"
             % (counts.get("nodes", 0), counts.get("edges", 0),
                counts.get("contracts_with_verdict", 0),
                counts.get("contracts_total", 0)))
        + "\n"
    )
    sys.stdout.write(
        clip("coverage: experiments %d/%d dirs with node, contracts unknown=%d"
             % (coverage.get("experiments_dirs_with_node", 0),
                coverage.get("experiments_dirs_total", 0),
                coverage.get("contracts_unknown", 0)))
        + "\n"
    )
    sys.stdout.write(
        clip("nodes: " + " ".join("%s=%d" % kv
             for kv in (counts.get("nodes_by_type") or {}).items())) + "\n"
    )
    sys.stdout.write(
        clip("edges: " + " ".join("%s=%d" % kv
             for kv in (counts.get("edges_by_type") or {}).items())) + "\n"
    )
    sys.stdout.write(
        clip("contract verdicts: " + " ".join("%s=%d" % kv
             for kv in verdict_dist.most_common())) + "\n"
    )
    sys.stdout.write(
        clip("rh outcomes: " + " ".join("%s=%d" % kv
             for kv in outcome_dist.most_common())) + "\n"
    )
    sys.stdout.write(
        clip("scorecard: " + " ".join("%s=%d" % kv
             for kv in sc_dist.most_common())) + "\n"
    )
    sys.stdout.write(
        clip("experiments: " + " ".join("%s=%d" % kv
             for kv in exp_dist.most_common())) + "\n"
    )
    v2 = counts.get("v2") or {}
    if v2:
        v2line = ("v2: claim_contracts=%d transitions=%d constraints=%d "
                  "failure_scopes=%d skipped=%d"
                  % (v2.get("claim_contracts", 0), v2.get("transitions", 0),
                     v2.get("constraints", 0), v2.get("failure_scopes", 0),
                     v2.get("skipped", 0)))
        sys.stdout.write(clip(v2line) + "\n")
    cycles = g.meta.get("cycles") or []
    n_pure = sum(1 for c in cycles
                 if isinstance(c, dict) and c.get("classified") == "depends_on_pure")
    sys.stdout.write(
        clip("cycles: %d (depends_on_pure=%d GATE-rot, supersedes_involved=%d Warnung)"
             % (len(cycles), n_pure, len(cycles) - n_pure)) + "\n")
    sys.stdout.write(
        clip("claim markers: " + " ".join("[%s]=%d" % kv
             for kv in marker_dist.most_common())) + "\n"
    )
    return 0


def _print_edge_group(g: Graph, label, edges, direction):
    """direction 'out': show dst; 'in': show src.  Aggregate stated_in."""
    if not edges:
        return
    by_type = defaultdict(list)
    for e in edges:
        by_type[e["type"]].append(e["dst"] if direction == "out" else e["src"])
    for etype in sorted(by_type):
        targets = by_type[etype]
        if etype == "stated_in":
            docs = Counter(t.split(":")[1] for t in targets)
            bits = ["%s (%d sections)" % kv for kv in sorted(docs.items())]
            sys.stdout.write(clip("  %s %s %s" % (label, etype, "; ".join(bits))) + "\n")
            continue
        shown = targets[:10]
        line = "  %s %s %s" % (label, etype, ", ".join(t.split(":", 1)[-1] for t in shown))
        if len(targets) > 10:
            line += "  ... (+%d more)" % (len(targets) - 10)
        sys.stdout.write(clip(line) + "\n")


def cmd_claim(g: Graph, arg, as_json):
    nid = as_claim_id(g, arg)
    if nid is None:
        sys.stderr.write("no such claim: %s\n" % arg)
        return 1
    n = g.by_id[nid]
    if as_json:
        emit_json({
            "node": n,
            "outgoing": g.out_edges.get(nid, []),
            "incoming": g.in_edges.get(nid, []),
        })
        return 0
    a = n["attrs"]
    markers = "".join("[%s]" % m for m in (a.get("markers") or [])) or "[-]"
    sys.stdout.write(clip("%s  %s  active=%s" % (nid, markers, a.get("active"))) + "\n")
    sys.stdout.write(clip("  status: %s" % a.get("status_raw")) + "\n")
    for key in ("unresolved", "unresolved_deps", "unresolved_locs"):
        if a.get(key):
            sys.stdout.write(clip("  %s: %s" % (key, ", ".join(a[key][:8]))) + "\n")
    _print_edge_group(g, "->", g.out_edges.get(nid, []), "out")
    _print_edge_group(g, "<-", g.in_edges.get(nid, []), "in")
    return 0


def cmd_tried(g: Graph, pattern, limit, as_json):
    try:
        cre = re.compile(pattern, re.I)
    except re.error as exc:
        sys.stderr.write("bad regex: %s\n" % exc)
        return 2
    hits = []
    for n in g.nodes:
        a = n["attrs"]
        if n["type"] == "contract":
            parts = [n["label"], a.get("question") or "", a.get("verdict_raw") or "",
                     a.get("summary_de") or ""]
            for f in a.get("findings") or []:
                parts.append(f.get("text") or "")
                parts.append(f.get("section") or "")
            for pair in a.get("claims_tested") or []:
                if isinstance(pair, (list, tuple)) and pair:
                    parts.append(str(pair[0]))
                else:
                    parts.append(str(pair))
            blob = "\n".join(parts)
            if cre.search(blob):
                hits.append(("contract", n))
        elif n["type"] == "rh":
            blob = "\n".join(str(x) for x in (
                n["label"], a.get("mechanism") or "", a.get("question") or "",
                a.get("family") or "", a.get("round") or ""))
            if cre.search(blob):
                hits.append(("rh", n))
        elif n["type"] == "scorecard":
            blob = "%s\n%s" % (a.get("domain") or "", a.get("observable") or "")
            if cre.search(blob):
                hits.append(("scorecard", n))
        elif n["type"] == "lean":
            blob = "\n".join([
                n["label"], a.get("module") or "", a.get("header_comment") or "",
                " ".join(d.get("name", "") for d in (a.get("declarations") or [])),
            ])
            if cre.search(blob):
                hits.append(("lean", n))
    hits.sort(key=lambda kn: (recency_key(kn[0], kn[1]), kn[1]["label"]), reverse=True)
    shown = hits[:limit]
    if as_json:
        emit_json([{"kind": k, "node": n} for k, n in shown])
        return 0
    sys.stdout.write(clip("tried /%s/  n=%d (showing %d)" % (pattern, len(hits), len(shown))) + "\n")
    sys.stdout.write("kind      | date       | verdict/outcome            | failure_class        | name\n")
    for kind, n in shown:
        a = n["attrs"]
        if kind == "contract":
            date, verdict = fmt_date(a.get("date")), a.get("verdict_raw") or "?"
            fclass = a.get("verdict_class") or "-"
        elif kind == "rh":
            date, verdict = a.get("round") or "-", a.get("outcome") or "?"
            fclass = a.get("failure_class") or "-"
        elif kind == "lean":
            date = "-"
            verdict = "%d thm/%d sorry" % (a.get("n_theorems") or 0,
                                           a.get("n_sorry") or 0)
            fclass = "lean"
        else:
            date, verdict, fclass = "-", a.get("status") or "?", a.get("evidence_class") or "-"
        sys.stdout.write(clip("%-9s | %-10s | %-26.26s | %-20.20s | %s"
                              % (kind, date, verdict, fclass, n["label"])) + "\n")
    return 0


def cmd_kills(g: Graph, pattern, limit, as_json):
    cre = None
    if pattern:
        try:
            cre = re.compile(pattern, re.I)
        except re.error as exc:
            sys.stderr.write("bad regex: %s\n" % exc)
            return 2
    hits = []
    for n in g.nodes:
        a = n["attrs"]
        kind = None
        if n["type"] == "rh" and a.get("outcome") == "KILLED":
            kind = "rh"
        elif n["type"] == "contract" and a.get("verdict_class") in ("killed", "refuted", "fail"):
            kind = "contract"
        elif n["type"] == "scorecard" and a.get("status") == "kill_channel":
            kind = "scorecard"
        if kind is None:
            continue
        if cre is not None:
            blob = "\n".join(str(x) for x in (
                n["label"], a.get("mechanism") or "", a.get("question") or "",
                a.get("observable") or "", a.get("failure_class") or "",
                a.get("verdict_raw") or ""))
            if not cre.search(blob):
                continue
        hits.append((kind, n))
    hits.sort(key=lambda kn: (recency_key(kn[0], kn[1]), kn[1]["label"]), reverse=True)
    shown = hits[:limit]
    if as_json:
        emit_json([{"kind": k, "node": n} for k, n in shown])
        return 0
    label = "kills" + ((" /%s/" % pattern) if pattern else "")
    sys.stdout.write(clip("%s  n=%d (showing %d)" % (label, len(hits), len(shown))) + "\n")
    sys.stdout.write("kind      | date       | outcome/verdict | failure_class        | name\n")
    for kind, n in shown:
        a = n["attrs"]
        if kind == "contract":
            date, verdict = fmt_date(a.get("date")), a.get("verdict_raw") or "?"
            fclass = a.get("verdict_class") or "-"
        elif kind == "rh":
            date, verdict = a.get("round") or "-", "KILLED"
            fclass = a.get("failure_class") or "-"
        else:
            date, verdict, fclass = "-", "kill_channel", a.get("evidence_class") or "-"
        sys.stdout.write(clip("%-9s | %-10s | %-15.15s | %-20.20s | %s"
                              % (kind, date, verdict, fclass, n["label"])) + "\n")
    return 0


def cmd_open(g: Graph, limit, as_json):
    open_claims = [
        n for n in g.nodes
        if n["type"] == "claim"
        and ("O" in (n["attrs"].get("markers") or [])
             or (n["attrs"].get("status_raw") or "").startswith("Open"))
    ]
    open_claims.sort(key=lambda n: (not n["label"].startswith("GATE."), n["label"]))
    rh_open = [n for n in g.nodes if n["type"] == "rh" and n["attrs"].get("outcome") == "OPEN"]
    by_family = defaultdict(list)
    for n in rh_open:
        by_family[n["attrs"].get("family") or "-"].append(n["label"])
    payload = {
        "open_claims": [n["label"] for n in open_claims],
        "rh_open_by_family": {k: len(v) for k, v in sorted(by_family.items())},
    }
    if as_json:
        emit_json(payload)
        return 0
    sys.stdout.write(clip("open claims (marker [O] or status Open*)  n=%d" % len(open_claims)) + "\n")
    for n in open_claims[:limit]:
        sys.stdout.write(clip("  %s  %s" % (n["label"], n["attrs"].get("status_raw"))) + "\n")
    if len(open_claims) > limit:
        sys.stdout.write(clip("  ... (+%d more, --limit)" % (len(open_claims) - limit)) + "\n")
    sys.stdout.write(clip("rh OPEN  n=%d (by family)" % len(rh_open)) + "\n")
    for fam, paths in sorted(by_family.items(), key=lambda kv: -len(kv[1])):
        sys.stdout.write(clip("  %-32s %d" % (fam, len(paths))) + "\n")
    return 0


def cmd_dossier(g: Graph, nid, as_json):
    n = g.node(nid) or g.node("claim:" + nid)
    if n is None:
        # tolerant suffix match (e.g. contract name without prefix)
        cand = [x for x in g.nodes if x["id"].endswith(":" + nid)]
        if len(cand) == 1:
            n = cand[0]
    if n is None:
        sys.stderr.write("no such node: %s\n" % nid)
        return 1
    nid = n["id"]
    if as_json:
        emit_json({
            "node": n,
            "outgoing": g.out_edges.get(nid, []),
            "incoming": g.in_edges.get(nid, []),
        })
        return 0
    sys.stdout.write(clip("--- %s (%s) ---" % (nid, n["type"])) + "\n")
    for key in sorted(n["attrs"]):
        val = n["attrs"][key]
        if val in (None, "", [], {}):
            continue
        if key == "findings" and isinstance(val, list):
            sys.stdout.write("findings:\n")
            for f in val:
                sys.stdout.write(clip("  [%s] (%s) %s"
                                      % (f.get("kind"), f.get("section") or "-",
                                         f.get("text"))) + "\n")
            continue
        if key == "declarations" and isinstance(val, list):
            sys.stdout.write("declarations:\n")
            for d in val:
                line = "  %s %s: %s" % (d.get("kind"), d.get("name"),
                                        d.get("signature"))
                if d.get("doc"):
                    line += "  -- " + str(d["doc"])
                sys.stdout.write(clip(line) + "\n")
            continue
        sys.stdout.write(clip("%s: %s" % (key, val)) + "\n")
    sys.stdout.write("edges out:\n")
    _print_edge_group(g, "->", g.out_edges.get(nid, []), "out")
    sys.stdout.write("edges in:\n")
    _print_edge_group(g, "<-", g.in_edges.get(nid, []), "in")
    return 0


def cmd_findings(g: Graph, pattern, limit, as_json):
    try:
        cre = re.compile(pattern, re.I)
    except re.error as exc:
        sys.stderr.write("bad regex: %s\n" % exc)
        return 2
    hits = []
    for n in g.nodes:
        if n["type"] == "contract":
            a = n["attrs"]
            for f in a.get("findings") or []:
                blob = "%s\n%s\n%s" % (f.get("text") or "", f.get("section") or "",
                                       n["label"])
                if cre.search(blob):
                    hits.append((a.get("date") or "", n["label"], f))
        elif n["type"] == "lean":
            a = n["attrs"]
            blob = "\n".join([
                n["label"], a.get("header_comment") or "",
                " ".join(d.get("name", "") for d in (a.get("declarations") or [])),
            ])
            if cre.search(blob):
                hits.append(("", n["label"], {
                    "kind": "lean",
                    "text": a.get("header_comment") or n["label"],
                    "section": a.get("module"),
                }))
    hits.sort(key=lambda row: (row[0], row[1]), reverse=True)
    shown = hits[:limit]
    if as_json:
        emit_json([{"date": d, "contract": c, "finding": f} for d, c, f in shown])
        return 0
    sys.stdout.write(clip("findings /%s/  n=%d (showing %d)"
                          % (pattern, len(hits), len(shown))) + "\n")
    sys.stdout.write("kind     | date       | contract                             | text\n")
    for d, c, f in shown:
        sys.stdout.write(clip("%-8s | %-10s | %-36.36s | %s"
                              % (f.get("kind"), fmt_date(d), c,
                                 f.get("text"))) + "\n")
    return 0


def cmd_lean(g: Graph, pattern, limit, as_json):
    try:
        cre = re.compile(pattern, re.I)
    except re.error as exc:
        sys.stderr.write("bad regex: %s\n" % exc)
        return 2
    hits = []
    for n in g.nodes:
        if n["type"] != "lean":
            continue
        a = n["attrs"]
        blob = "\n".join([
            n["label"],
            a.get("module") or "",
            a.get("header_comment") or "",
            " ".join(d.get("name", "") for d in (a.get("declarations") or [])),
        ])
        if cre.search(blob):
            hits.append(n)
    hits.sort(key=lambda n: n["label"])
    shown = hits[:limit]
    if as_json:
        emit_json(shown)
        return 0
    sys.stdout.write(clip("lean /%s/  n=%d (showing %d)" % (pattern, len(hits), len(shown))) + "\n")
    sys.stdout.write("datei | theoreme | sorrys | imports\n")
    for n in shown:
        a = n["attrs"]
        row = "%s | %d | %d | %d repo + %d mathlib" % (
            n["label"], a.get("n_theorems") or 0, a.get("n_sorry") or 0,
            len(a.get("imports_repo") or []), a.get("n_imports_mathlib") or 0)
        sys.stdout.write(clip(row) + "\n")
    return 0


def cmd_recheck(g: Graph, as_json):
    """Claims whose verified_by scripts changed on disk since the build
    (hash binding, schema Punkt 6: changed source != automatically false)."""
    rows = []
    for e in g.edges:
        if e["type"] != "verified_by":
            continue
        status = script_hash_status(g, e["dst"])
        if status in ("aktuell", "ohne Hash"):
            continue
        rows.append({
            "claim": e["src"].replace("claim:", ""),
            "script": e["dst"].replace("script:", ""),
            "status": status,
        })
    rows.sort(key=lambda r: (r["status"], r["claim"]))
    if as_json:
        emit_json(rows)
        return 0
    sys.stdout.write(clip("recheck  n=%d" % len(rows)) + "\n")
    sys.stdout.write("claim | script | markierung\n")
    for r in rows:
        if r["status"] == "GEÄNDERT":
            note = "erneut zu prüfen (Quelle geändert — Aussage NICHT automatisch falsch)"
        else:
            note = "Script-Datei fehlt — Hash im Graph ohne Quelle"
        sys.stdout.write(clip("%s | %s | %s" % (r["claim"], r["script"], note)) + "\n")
    return 0


def cmd_why(g: Graph, arg, as_json):
    nid = as_claim_id(g, arg)
    if nid is None:
        sys.stderr.write("no such claim: %s\n" % arg)
        return 1
    n = g.by_id[nid]
    a = n["attrs"]
    contract = a.get("contract") or {}
    deps = [e["dst"] for e in g.out_edges.get(nid, []) if e["type"] == "depends_on"]
    verified = [e["dst"] for e in g.out_edges.get(nid, []) if e["type"] == "verified_by"]
    payload = {
        "claim": nid, "status_raw": a.get("status_raw"), "markers": a.get("markers"),
        "contract": contract or None,
        "verified_by": [{"script": s.replace("script:", ""),
                         "hash": script_hash_status(g, s)} for s in verified],
        "depends_on": [{"claim": d.replace("claim:", ""),
                        "status": (g.node(d) or {}).get("attrs", {}).get("status_raw")}
                       for d in deps],
        "unresolved_deps": a.get("unresolved_deps") or [],
    }
    if as_json:
        emit_json(payload)
        return 0
    markers = "".join("[%s]" % m for m in (a.get("markers") or [])) or "[-]"
    sys.stdout.write(clip("why %s  %s" % (nid, markers)) + "\n")
    if contract:
        sys.stdout.write(clip("  statement: %s" % contract.get("statement")) + "\n")
        for q in contract.get("quantifiers") or []:
            sys.stdout.write(clip("  quantor: %s" % q) + "\n")
        if contract.get("limit"):
            sys.stdout.write(clip("  limit: %s" % contract.get("limit")) + "\n")
        prems = contract.get("premises") or []
        if prems:
            sys.stdout.write("  premises (KONJUNKTIV — alle zusammen nötig):\n")
            for i, p in enumerate(prems, 1):
                sys.stdout.write(clip("    P%d. %s" % (i, p)) + "\n")
        for cs in contract.get("chosen_structures") or []:
            sys.stdout.write(clip("  chosen_structure: %s" % cs) + "\n")
        if contract.get("epistemic"):
            sys.stdout.write(clip("  epistemic: %s" % contract.get("epistemic")) + "\n")
        proof = contract.get("proof") or {}
        if proof:
            sys.stdout.write(clip("  proof: %s | %s | %s"
                                  % (proof.get("script"), proof.get("checked_relation"),
                                     proof.get("scope"))) + "\n")
    else:
        sys.stdout.write(clip("  status: %s" % a.get("status_raw")) + "\n")
    for item in payload["verified_by"]:
        sys.stdout.write(clip("  verified_by: %s (Hash: %s)"
                              % (item["script"], item["hash"])) + "\n")
    if payload["depends_on"]:
        sys.stdout.write("  depends_on (1 Ebene):\n")
        for d in payload["depends_on"]:
            sys.stdout.write(clip("    %s — %s" % (d["claim"], d["status"])) + "\n")
    if payload["unresolved_deps"]:
        sys.stdout.write(clip("  unresolved_deps: %s"
                              % ", ".join(payload["unresolved_deps"][:8])) + "\n")
    if "O" in (a.get("markers") or []):
        sys.stdout.write("  marker [O]: offene Reste vorhanden\n")
    return 0


def cmd_fit(g: Graph, pattern, limit, as_json):
    """Constraints + transitions touching an object/theme."""
    try:
        cre = re.compile(pattern, re.I)
    except re.error as exc:
        sys.stderr.write("bad regex: %s\n" % exc)
        return 2
    hits = []
    for n in g.nodes:
        a = n["attrs"]
        if n["type"] == "constraint":
            blob = "\n".join(str(x) for x in (
                n["label"], a.get("on_object") or "", a.get("requirement") or "",
                a.get("raised_by") or ""))
            if cre.search(blob):
                hits.append(n)
        elif n["type"] == "transition":
            blob = "\n".join(str(x) for x in (
                n["label"], a.get("from_raw") or "", a.get("to_raw") or "",
                a.get("map") or "", a.get("notes") or "",
                " ".join(a.get("preserves") or []),
                " ".join(a.get("fails_to_preserve") or [])))
            if cre.search(blob):
                hits.append(n)
    hits.sort(key=lambda n: n["id"])
    shown = hits[:limit]
    if as_json:
        emit_json(shown)
        return 0
    sys.stdout.write(clip("fit /%s/  n=%d" % (pattern, len(hits))) + "\n")
    sys.stdout.write("typ | id | status | berührt\n")
    for n in shown:
        a = n["attrs"]
        if n["type"] == "constraint":
            touched = "on_object=%s (raised_by %s)" % (a.get("on_object"), a.get("raised_by"))
            status = "-"
        else:
            touched = "%s -> %s" % (a.get("from_raw"), a.get("to_raw"))
            status = a.get("status") or "-"
        sys.stdout.write(clip("%s | %s | %s | %s"
                              % (n["type"], n["label"], status, touched)) + "\n")
    return 0


def _open_claims(g: Graph):
    out = []
    for n in g.nodes:
        if n["type"] != "claim":
            continue
        a = n["attrs"]
        if ("O" in (a.get("markers") or [])
                or (a.get("status_raw") or "").startswith("Open")):
            out.append(n)
    return out


def cmd_next(g: Graph, goal, limit, as_json):
    """Ranked open fronts.  HEURISTIC score, not a proof ordering:
    2x transitive dependents + 3x gate reference + 1x has checker
    - 2x failing contracts testing it."""
    radj = defaultdict(set)
    for e in g.edges:
        if e["type"] == "depends_on":
            radj[e["dst"]].add(e["src"])
    fail_tests = Counter()
    for e in g.edges:
        if e["type"] != "tests" or not e["src"].startswith("contract:"):
            continue
        src = g.node(e["src"])
        if src and (src["attrs"].get("verdict_class") in ("fail", "killed", "refuted")):
            fail_tests.update([e["dst"]])
    verified_claims = {e["src"] for e in g.edges if e["type"] == "verified_by"}

    def n_dependents(nid):
        seen = set()
        queue = [nid]
        while queue:
            cur = queue.pop()
            for nb in radj.get(cur, ()):
                if nb not in seen:
                    seen.add(nb)
                    queue.append(nb)
        return len(seen)

    candidates = _open_claims(g)
    if goal:
        gid = as_claim_id(g, goal)
        if gid is None:
            sys.stderr.write("no such goal claim: %s\n" % goal)
            return 1
        # ancestors of the goal (what the goal transitively depends on)
        ancestors = set()
        queue = [gid]
        while queue:
            cur = queue.pop()
            for e in g.out_edges.get(cur, []):
                if e["type"] == "depends_on" and e["dst"] not in ancestors:
                    ancestors.add(e["dst"])
                    queue.append(e["dst"])
        candidates = [n for n in candidates if n["id"] in ancestors]
    rows = []
    for n in candidates:
        nid = n["id"]
        dep = n_dependents(nid)
        gate = 1 if "GATE." in n["label"] else 0
        checker = 1 if nid in verified_claims else 0
        fails = fail_tests.get(nid, 0)
        score = 2 * dep + 3 * gate + 1 * checker - 2 * fails
        why = []
        if dep:
            why.append("%d transitive Abhängige" % dep)
        if gate:
            why.append("GATE-Bezug")
        if checker:
            why.append("Checker vorhanden")
        if fails:
            why.append("%d fail/kill-Contracts" % fails)
        rows.append({"claim": n["label"], "score": score,
                     "why": "; ".join(why) or "-",
                     "status": (n["attrs"].get("status_raw") or "")[:80]})
    rows.sort(key=lambda r: (-r["score"], r["claim"]))
    shown = rows[:limit]
    if as_json:
        emit_json({"heuristic": True, "goal": goal, "rows": shown})
        return 0
    sys.stdout.write(clip("next%s  n=%d  (HEURISTIK: 2xAbhängige +3xGATE +1xChecker -2xfail-Contracts)"
                          % ((" goal=" + goal) if goal else "", len(rows))) + "\n")
    sys.stdout.write("claim | score | warum\n")
    for r in shown:
        sys.stdout.write(clip("%s | %d | %s" % (r["claim"], r["score"], r["why"])) + "\n")
    return 0


def cmd_contradictions(g: Graph, limit, as_json):
    """contradicts edges + refutes/no_go findings (LLM-adjudicated first)
    + scorecard tensions."""
    rows = []
    for e in g.edges:
        if e["type"] == "contradicts":
            src = g.node(e["src"])
            rows.append({
                "date": (src or {}).get("attrs", {}).get("date") or "",
                "art": "contradicts",
                "quelle": e["src"].replace("contract:", ""),
                "text": "vs " + e["dst"],
                "llm": True,
            })
    for n in g.nodes:
        if n["type"] == "contract":
            a = n["attrs"]
            for f in a.get("findings") or []:
                if f.get("kind") in ("refutes", "no_go"):
                    rows.append({
                        "date": a.get("date") or "",
                        "art": f.get("kind"),
                        "quelle": n["label"],
                        "text": f.get("text"),
                        "llm": f.get("override") == "llm",
                    })
        elif n["type"] == "scorecard" and n["attrs"].get("status") == "tension":
            rows.append({
                "date": "",
                "art": "tension",
                "quelle": n["label"],
                "text": n["attrs"].get("observable"),
                "llm": False,
            })
    rows.sort(key=lambda r: r["date"], reverse=True)
    # stable re-sort: LLM-adjudicated findings first, dates kept within groups
    rows.sort(key=lambda r: 0 if r["llm"] else 1)
    shown = rows[:limit]
    if as_json:
        emit_json(shown)
        return 0
    sys.stdout.write(clip("contradictions  n=%d" % len(rows)) + "\n")
    sys.stdout.write("datum | art | quelle | text\n")
    for r in shown:
        sys.stdout.write(clip("%s | %s | %s | %s"
                              % (fmt_date(r["date"]), r["art"], r["quelle"],
                                 r["text"])) + "\n")
    return 0


def cmd_brief(g: Graph, pattern, as_json):
    """Session work package for a topic: open claims, last verdicts, active
    failure scopes/kills (with not_excluded guards), top-3 next candidates."""
    try:
        cre = re.compile(pattern, re.I)
    except re.error as exc:
        sys.stderr.write("bad regex: %s\n" % exc)
        return 2
    open_hits = [n for n in _open_claims(g)
                 if cre.search(n["label"]) or cre.search(n["attrs"].get("status_raw") or "")]
    verdict_hits = []
    for n in g.nodes:
        if n["type"] != "contract":
            continue
        a = n["attrs"]
        blob = "\n".join([n["label"], a.get("question") or "",
                          a.get("summary_de") or ""])
        if cre.search(blob):
            verdict_hits.append(n)
    verdict_hits.sort(key=lambda n: (n["attrs"].get("date") or "", n["label"]),
                      reverse=True)
    failures = [n for n in g.nodes if n["type"] == "failure"
                and cre.search(n["label"] + " " + (n["attrs"].get("target") or ""))]
    kills = []
    for n in g.nodes:
        a = n["attrs"]
        if n["type"] == "rh" and a.get("outcome") == "KILLED":
            blob = "\n".join(str(x) for x in (n["label"], a.get("mechanism") or "",
                                              a.get("question") or ""))
            if cre.search(blob):
                kills.append(n)
        elif n["type"] == "contract" and a.get("verdict_class") in ("killed", "refuted", "fail"):
            if cre.search(n["label"] + " " + (a.get("summary_de") or "")):
                kills.append(n)
    # top-3 next candidates within the topic
    sub_scores = []
    radj = defaultdict(set)
    for e in g.edges:
        if e["type"] == "depends_on":
            radj[e["dst"]].add(e["src"])
    verified_claims = {e["src"] for e in g.edges if e["type"] == "verified_by"}
    for n in open_hits:
        nid = n["id"]
        seen = set()
        queue = [nid]
        while queue:
            cur = queue.pop()
            for nb in radj.get(cur, ()):
                if nb not in seen:
                    seen.add(nb)
                    queue.append(nb)
        score = 2 * len(seen) + (3 if "GATE." in n["label"] else 0) \
            + (1 if nid in verified_claims else 0)
        sub_scores.append((score, n["label"]))
    sub_scores.sort(key=lambda x: (-x[0], x[1]))
    payload = {
        "pattern": pattern,
        "generated": g.meta.get("generated"),
        "open_claims": [n["label"] for n in open_hits],
        "last_verdicts": [
            {"date": n["attrs"].get("date"), "contract": n["label"],
             "verdict": n["attrs"].get("verdict_raw")}
            for n in verdict_hits[:10]],
        "failure_scopes": [
            {"id": n["label"], "target": n["attrs"].get("target"),
             "not_excluded": n["attrs"].get("not_excluded") or []}
            for n in failures],
        "kills": [{"kind": n["type"], "name": n["label"]} for n in kills[:15]],
        "next_top3": [{"claim": c, "score": s} for s, c in sub_scores[:3]],
    }
    if as_json:
        emit_json(payload)
        return 0
    out = []
    out.append("brief /%s/  (graph generated %s)" % (pattern, g.meta.get("generated")))
    out.append("offene Claims (%d):" % len(open_hits))
    for n in open_hits[:12]:
        out.append("  %s — %s" % (n["label"], clip(n["attrs"].get("status_raw"), 70)))
    out.append("letzte Verdicts (%d):" % len(verdict_hits))
    for n in verdict_hits[:10]:
        a = n["attrs"]
        out.append("  %s %s: %s" % (fmt_date(a.get("date")), n["label"],
                                    clip(a.get("verdict_raw") or "?", 60)))
    out.append("aktive failure_scopes (%d):" % len(failures))
    for n in failures[:8]:
        out.append("  %s: %s" % (n["label"], clip(n["attrs"].get("target"), 70)))
        for guard in (n["attrs"].get("not_excluded") or [])[:3]:
            out.append("    NICHT ausgeschlossen: %s" % clip(guard, 80))
    out.append("kills im Thema (%d):" % len(kills))
    for n in kills[:8]:
        out.append("  [%s] %s" % (n["type"], n["label"]))
    out.append("next Top-3 (Heuristik):")
    for s, c in sub_scores[:3]:
        out.append("  %s (score %d)" % (c, s))
    for line in out[:60]:
        sys.stdout.write(clip(line) + "\n")
    return 0


def cmd_path(g: Graph, arg_a, arg_b, as_json):
    a = as_claim_id(g, arg_a)
    b = as_claim_id(g, arg_b)
    if a is None or b is None:
        sys.stderr.write("unknown claim: %s\n" % (arg_a if a is None else arg_b))
        return 1
    adj = defaultdict(set)
    for e in g.edges:
        if e["type"] in ("depends_on", "supersedes"):
            adj[e["src"]].add(e["dst"])
            adj[e["dst"]].add(e["src"])
    # BFS, ungerichtet
    prev = {a: None}
    queue = [a]
    found = False
    while queue:
        nxt = []
        for cur in queue:
            if cur == b:
                found = True
                break
            for nb in adj.get(cur, ()):
                if nb not in prev:
                    prev[nb] = cur
                    nxt.append(nb)
        if found:
            break
        queue = nxt
    if not found:
        if as_json:
            emit_json({"path": [], "found": False})
            return 1
        sys.stdout.write("no depends_on/supersedes path: %s  ~X~  %s\n" % (a, b))
        return 1
    path = []
    cur = b
    while cur is not None:
        path.append(cur)
        cur = prev[cur]
    path.reverse()
    if as_json:
        emit_json({"path": path, "found": True, "length": len(path) - 1})
        return 0
    sys.stdout.write(clip("path %s -> %s  (edges=%d)" % (a, b, len(path) - 1)) + "\n")
    for i, nid in enumerate(path):
        sys.stdout.write(clip("  %d. %s" % (i + 1, nid.replace("claim:", ""))) + "\n")
    return 0


# --------------------------------------------------------------------------

def build_parser():
    common = argparse.ArgumentParser(add_help=False)
    common.add_argument("--json", action="store_true", help="machine-readable JSON output")
    parser = argparse.ArgumentParser(
        prog="theorycat",
        description="Query the generated TFPT theory graph (verification/theory_graph.json).",
        parents=[common],
    )
    parser.add_argument("--no-rebuild", action="store_true",
                        help="skip the lazy staleness rebuild")
    sub = parser.add_subparsers(dest="cmd", required=True)

    sub.add_parser("stats", parents=[common], help="counts + verdict/outcome distributions")

    p = sub.add_parser("claim", parents=[common], help="claim node + compact edges")
    p.add_argument("id")

    p = sub.add_parser("tried", parents=[common],
                       help="contracts + RH records + scorecard rows matching a regex")
    p.add_argument("regex")
    p.add_argument("--limit", type=int, default=30, metavar="N")

    p = sub.add_parser("kills", parents=[common],
                       help="everything killed (rh KILLED + contract killed/refuted/fail + scorecard kill_channel)")
    p.add_argument("regex", nargs="?", default=None)
    p.add_argument("--limit", type=int, default=30, metavar="N")

    p = sub.add_parser("open", parents=[common],
                       help="open fronts: claims [O]/Open* + rh OPEN by family")
    p.add_argument("--limit", type=int, default=30, metavar="N")

    p = sub.add_parser("dossier", parents=[common], help="full node + all edges")
    p.add_argument("node_id")

    p = sub.add_parser("findings", parents=[common],
                       help="verdict-carrying sentences (refutes|no_go|supports|open) matching a regex")
    p.add_argument("regex")
    p.add_argument("--limit", type=int, default=30, metavar="N")

    p = sub.add_parser("lean", parents=[common],
                       help="lean files matching regex (path/header/declarations)")
    p.add_argument("regex")
    p.add_argument("--limit", type=int, default=30, metavar="N")

    p = sub.add_parser("recheck", parents=[common],
                       help="claims whose verified_by scripts changed on disk (hash binding)")

    p = sub.add_parser("why", parents=[common],
                       help="claim contract: statement, premises, proof, hash status")
    p.add_argument("id")

    p = sub.add_parser("fit", parents=[common],
                       help="constraints + transitions touching an object/theme")
    p.add_argument("regex")
    p.add_argument("--limit", type=int, default=30, metavar="N")

    p = sub.add_parser("next", parents=[common],
                       help="ranked open fronts (heuristic score)")
    p.add_argument("--goal", default=None, metavar="CLAIM")
    p.add_argument("--limit", type=int, default=20, metavar="N")

    p = sub.add_parser("contradictions", parents=[common],
                       help="contradicts edges + refutes/no_go findings + tensions")
    p.add_argument("--limit", type=int, default=30, metavar="N")

    p = sub.add_parser("brief", parents=[common],
                       help="session work package for a topic regex (<60 lines)")
    p.add_argument("regex")

    p = sub.add_parser("path", parents=[common],
                       help="shortest depends_on/supersedes path between two claims (BFS)")
    p.add_argument("claim_a")
    p.add_argument("claim_b")
    return parser


def main(argv=None):
    parser = build_parser()
    args = parser.parse_args(argv)
    if not os.path.isfile(GRAPH_PATH):
        sys.stderr.write(
            "theory graph missing: run: python verification/build_theory_graph.py\n"
        )
        sys.exit(2)
    maybe_rebuild(no_rebuild=bool(getattr(args, "no_rebuild", False)))
    g = Graph(load_graph())
    as_json = bool(getattr(args, "json", False))
    if args.cmd == "stats":
        return cmd_stats(g, as_json)
    if args.cmd == "claim":
        return cmd_claim(g, args.id, as_json)
    if args.cmd == "tried":
        return cmd_tried(g, args.regex, max(1, args.limit), as_json)
    if args.cmd == "kills":
        return cmd_kills(g, args.regex, max(1, args.limit), as_json)
    if args.cmd == "open":
        return cmd_open(g, max(1, args.limit), as_json)
    if args.cmd == "dossier":
        return cmd_dossier(g, args.node_id, as_json)
    if args.cmd == "findings":
        return cmd_findings(g, args.regex, max(1, args.limit), as_json)
    if args.cmd == "lean":
        return cmd_lean(g, args.regex, max(1, args.limit), as_json)
    if args.cmd == "recheck":
        return cmd_recheck(g, as_json)
    if args.cmd == "why":
        return cmd_why(g, args.id, as_json)
    if args.cmd == "fit":
        return cmd_fit(g, args.regex, max(1, args.limit), as_json)
    if args.cmd == "next":
        return cmd_next(g, args.goal, max(1, args.limit), as_json)
    if args.cmd == "contradictions":
        return cmd_contradictions(g, max(1, args.limit), as_json)
    if args.cmd == "brief":
        return cmd_brief(g, args.regex, as_json)
    if args.cmd == "path":
        return cmd_path(g, args.claim_a, args.claim_b, as_json)
    parser.error("unknown command")
    return 2


if __name__ == "__main__":
    sys.exit(main())
