"""v564 -- CP.FIBER.PIN.01: the frame door of the CP mirror, decided (T178).

THE FRAME DOOR, AS ALGEBRA.  T177 (v561, verdict DEGENERATE) left the CP
mirror with two open items: R1 -- can a frame-coupled, scale-free,
character-covariant pi/3-carrier exist at all (the observed obstruction: the
(1, d, n) frame has only ONE oriented volume to normalise against) -- and
R2 -- which of the two degenerate Tier-2 characters is physical (the
sheet-odd reading matches CP.MU6.01: a preference, not a derivation).  T178
(contract FRAME.CARRIER, probe cp_frame_carrier_probe.py, 31/31, verdict
FIBER-PINNED) decided both at probe level; THIS module is the load-bearing
version of the exact cores.  It derives NOTHING about CP violation: every
statement is a THEOREM about the declared frame calculus, a certified
character account, or an exhibited non-uniqueness -- no marker of any
pre-existing contract moves.

[E] (1) THE EULER FACTORISATION (T178 H1).  The fiber acts on the frame by a
    SCALAR on one row (n -> rho n, the DUAL.FRAME.01 construction), so EVERY
    homogeneous polynomial block of n-degree m factorises exactly:
    P(rho n) = rho^m P(n) -- multilinear or not (checked on FULLY GENERIC
    homogeneous polynomials of degree 1..4 with symbolic coefficients, and on
    the concrete blocks det(1,d,n), <d,n>, <1,n>, <n,n>).  Consequence:
    every scale-free rational functional with fiber insertions decomposes as
    F = sum_k A_k Im(rho^k) with A_k REAL degree-0 frame ratios -- the fiber
    content is QUANTISED, the frame can only contribute real ratios.
[E] (2) THE NATURAL CLASS IS FIBER-ONLY (T178 H2; T177-R1, natural half,
    DECIDED NEGATIVE BY THEOREM).  Metric-free invariants of a vector tuple
    are generated by the volume-form brackets (first fundamental theorem,
    Weyl 1946 -- CITED class boundary, the one [C]-import of this module).
    On {1, d, n} the bracket enumeration is finite and checked exactly:
    exactly the 6 permutations of (1, d, n) are nonzero and all equal
    +-Delta; the other 21 brackets vanish identically in a GENERIC n.  One
    generator ==> every scale-free (n-degree-0) ratio is CONSTANT ==> the
    natural class contains NO frame-coupled scale-free functional.  T177's
    obstruction sentence ('one determinant only') is now a theorem.
[E] (3) THE METRIC DOOR IS NON-CANONICAL (T178 H3; T177-R1, metric half).
    Declaring a metric admits frame-coupled Tier-2 carriers -- and they are
    non-unique at BOTH levels.  Characters: Im(rho) Delta/<d,n> and
    Im(rho) Delta/<1,n> carry (chi_kappa, chi_sigma, chi_Ref) = (-1,-1,+1)
    (the odd Delta-power absorbs the deck reflection) while
    Im(rho) Delta^2/<n,n> carries (-1,-1,-1).  Values: the admissible
    normalisers contain the continuum q_t(n) = t n1^2 + n2^2 + n3^2 (deck-
    invariant for EVERY t, checked identically in (n, t)), giving carrier
    values 441 sin(pi/3)/(25 t + 117) -- strictly monotone in t.  NO
    canonical frame factor exists.  ANTI-NUMEROLOGY WIRED AS A CHECK: the
    exhibited values 21/8, 21/2, 441/142 are pairwise distinct and none is
    1 -- they are normaliser-relative frame data, and none is claimed.
[E] (4) THE SINGLE-SINE LEMMA (T178 H4; the pattern -- WHY T177 ended
    DEGENERATE).  On a mu_n fiber the nonzero carrier magnitudes
    {|Im(rho_n^k)|} form a ONE-element set iff n is crystallographic
    (n in {1,2,3,4,6}, equivalently phi(n) <= 2).  Proof in one exact line:
    sin(4 pi/n) - sin(2 pi/n) = 2 sin(pi/n) cos(3 pi/n), whose only zero on
    n >= 5 is n = 6; enumeration to n = 24 confirms and the totient
    criterion matches.  The compiler's two clocks -- mu4 (seam deck,
    j = 1728) and mu6 (CP fiber, j = 0) -- are exactly the two MAXIMAL
    single-sine fibers (the two CM points with extra automorphisms), so on
    them EVERY carrier emits the same sine: value-based pinning of
    functionals is impossible BY THEOREM, and T177's DEGENERATE verdict was
    forced, not found.  Mutation: on the non-CM fiber mu5 two carriers ARE
    separated by value (sin(2pi/5) != sin(4pi/5) exactly).
[E] (5) THE ANCHOR SELECTION (T178 H5; T177-R2, SELECTED).  The classical
    CP anchor -- the Jarlskog invariant on the TFPT CKM rebuild (v88,
    frozen delta per REG.FREEZE.01) -- has its own full character tuple
    under the three involutions (kappa = conjugation, sigma = sheet flip
    delta -> delta + pi, deck reflection V -> V Ref):
    (chi_kappa, chi_sigma, chi_Ref) = (-1, -1, -1), each certified at 40
    dps.  This tuple matches the sheet-ODD orientation class (V5, invariant
    core Im(rho) = sin(pi/3)) and NOT the sheet-even channel class P2 =
    (-1, +1, -1): of T177's two degenerate classes, exactly ONE matches the
    anchor.  The metric-class account sharpens it: the <d,n>/<1,n>-
    normalised frame carriers ((-1,-1,+1)) are ANCHOR-REJECTED, the
    <n,n>-family matches but carries the (3) continuum -- so the UNIQUE
    anchor-matching CANONICAL carrier is the fiber-pure V5.  Consistency:
    Im(rho^4) = -Im(rho) flips exactly as sin(delta + pi) = -sin(delta)
    (the CP.MU6.01 wiring), symbolically.

NAMED LIMITS AS LOAD-BEARING CONTENT (the claim INCLUDES them):
  (i)   The selection (5) is CONDITIONAL ON THE ANCHOR: Jarlskog 1985 is
        imported physics, so R2 is SELECTED inside declared groups, not
        derived; the word 'derived' appears nowhere for any CP statement.
  (ii)  The deck reflection column is the T177 DECLARED MODEL (D4 signed
        permutations, fiber action through Aut(mu6) = Z/2); the kappa and
        sigma columns are model-free.
  (iii) The Weyl FFT (brackets generate) is the cited class boundary [C];
        the in-file part (the enumeration on {1, d, n}) is exact and
        complete for the alternating blocks.
  (iv)  REG.FREEZE.01 untouched; the 3-vs-2 lambda_C^2 coefficient question
        untouched; NO marker moves; the CP residual is NOT closed -- it is
        RELOCATED with a proof: the invariant CP core is the fiber datum
        Im(rho) = sin(pi/3), and it provably CANNOT be made frame data
        without importing a non-canonical metric normaliser.
HONEST FENCES: no RH statement anywhere (finite exact statements about
roots of unity, 3x3 determinants, one 3x3 unitary matrix and one exact
trigonometric identity); Weyl 1946 / Hilbert 1893 (FFT), Jarlskog 1985,
Wolfenstein 1983, Barlow 1894 (crystallographic restriction), Euler
(homogeneity) named CLASSICAL as addresses.  Status: [E] exact identities
and certified numerics with mutation controls; sympy exact where possible;
Python-only, counted per GATE.WOLFRAM.02.  Discovery provenance:
  experiments/tfpt-discovery/cp_frame_carrier_probe.py (T178, 31/31,
  FIBER-PINNED)
"""
import mpmath as mp
import sympy as sp

from tfpt_constants import check, summary, reset, phi0, N_fam

# ---- the exact objects (all sympy-exact) ----------------------------------
RHO = sp.exp(sp.I * sp.pi / 3)                 # hexagonal CM unit, j = 0
E8_DEGREES = (2, 8, 12, 14, 18, 20, 24, 30)
SCALARON = 7

ONE = sp.Matrix([1, 1, 1])
D_VEC = sp.Matrix([sp.Rational(-1, 2), sp.Rational(-1, 2), 1])
N_VEC = sp.Matrix([5, -9, 6])

ROT = sp.Matrix([[1, 0, 0], [0, 0, -1], [0, 1, 0]])
REF = sp.Matrix([[1, 0, 0], [0, 0, 1], [0, 1, 0]])

n1, n2, n3, t = sp.symbols('n1 n2 n3 t', real=True)
z = sp.symbols('z')
N_SYM = sp.Matrix([n1, n2, n3])


def frame_det(third):
    return sp.Matrix([[1, 1, 1], list(D_VEC.T), list(third.T)]).det()


def run():
    reset()
    print("=" * 72)
    print("v564  CP.FIBER.PIN.01 -- the frame door of the CP mirror, "
          "decided (T178)")
    print("=" * 72)

    # ================================================================ S1
    print("\nS1 -- the Euler factorisation: the fiber factors off the frame "
          "(T178 H1)")
    ok_generic = True
    for m_deg in (1, 2, 3, 4):
        monos = [n1**i * n2**j * n3**(m_deg - i - j)
                 for i in range(m_deg + 1) for j in range(m_deg + 1 - i)]
        coeffs = sp.symbols('c0:%d' % len(monos))
        P = sum(c * mo for c, mo in zip(coeffs, monos))
        Pz = P.subs({n1: z * n1, n2: z * n2, n3: z * n3}, simultaneous=True)
        ok_generic &= (sp.simplify(sp.expand(Pz - z**m_deg * P)) == 0)
    check("S1.EULER [E] fully generic homogeneous polynomials of degree "
          "1..4 (3+6+10+15 symbolic coefficients) all satisfy "
          "P(z n) = z^m P(n) IDENTICALLY -- the fiber acts by a scalar on "
          "the n-row, so fiber and frame factor exactly for the whole "
          "polynomial class, multilinear or not (Euler)", ok_generic)
    ok_blocks = True
    for (bexpr, bdeg) in ((frame_det(N_SYM), 1), ((D_VEC.T * N_SYM)[0], 1),
                          ((ONE.T * N_SYM)[0], 1), ((N_SYM.T * N_SYM)[0], 2)):
        bz = bexpr.subs({n1: z * n1, n2: z * n2, n3: z * n3},
                        simultaneous=True)
        ok_blocks &= (sp.simplify(sp.expand(bz - z**bdeg * bexpr)) == 0)
    check("S1.BLOCKS [E] the four concrete blocks det(1,d,n), <d,n>, "
          "<1,n>, <n,n> factorise with degrees (1,1,1,2) identically in a "
          "generic n", ok_blocks)
    check("S1.QUANT [E] consequence on the instance: the fiber content of "
          "any degree-0 ratio is quantised to Im(rho^k) -- witness "
          "Im(rho^3 * (Delta <d,n>/<n,n>)) = Im(rho^3) * (21*8/142) = 0 "
          "exactly (rho^3 = -1 real)",
          sp.simplify(sp.im(sp.expand_complex(
              RHO**3 * sp.Rational(21 * 8, 142)))) == 0
          and sp.simplify(sp.im(sp.expand_complex(RHO**3))) == 0)

    # ================================================================ S2
    print("\nS2 -- the natural class is fiber-only: T177-R1 natural half, "
          "decided by theorem (T178 H2)")
    rows = {"1": ONE, "d": D_VEC, "n": N_SYM}
    nonzero = []
    for a in rows:
        for b in rows:
            for c in rows:
                det = sp.Matrix([list(rows[a].T), list(rows[b].T),
                                 list(rows[c].T)]).det()
                if sp.simplify(det) != 0:
                    nonzero.append((a, b, c))
    check("S2.ENUM [E] the bracket enumeration on {1, d, n}: exactly the 6 "
          "permutations of (1, d, n) are nonzero, all 21 brackets with a "
          "repeated row vanish identically in the GENERIC n",
          len(nonzero) == 6
          and all({a, b, c} == {"1", "d", "n"} for (a, b, c) in nonzero))
    ratios = {sp.simplify(sp.Matrix([list(rows[a].T), list(rows[b].T),
                                     list(rows[c].T)]).det()
                          / frame_det(N_SYM)) for (a, b, c) in nonzero}
    check("S2.GEN [E] all six nonzero brackets equal +-Delta (ratios "
          "{+1, -1}): the metric-free generator list is {Delta}, ONE "
          "element (completeness of 'brackets generate' = Weyl 1946 FFT, "
          "the cited class boundary [C])",
          ratios == {sp.Integer(1), sp.Integer(-1)})
    check("S2.THEOREM [E] one generator ==> every scale-free ratio is "
          "constant (Delta^a/Delta^a = 1 identically in the generic n) "
          "==> the natural class contains NO frame-coupled scale-free "
          "functional; with S1 its fiber content is exactly {Im(rho^k)}: "
          "FIBER-ONLY.  T177's R1 obstruction ('one determinant only') is "
          "now a THEOREM -- the natural half of R1 is decided, negative",
          sp.simplify(frame_det(N_SYM)**2 / frame_det(N_SYM)**2) == 1)

    # ================================================================ S3
    print("\nS3 -- the metric door is non-canonical: T177-R1 metric half "
          "(T178 H3)")
    check("S3.FRAMEDATA [E] the metric pairings at the TFPT point: "
          "<d,n> = 8, <1,n> = 2, <n,n> = 142, Delta = 21 = N_fam*scalaron "
          "-- three explicit metric-class carriers take values "
          "(21/8) sin(pi/3), (21/2) sin(pi/3), (441/142) sin(pi/3): all "
          "CARRIER-SIN, all scale-free, all frame-coupled (non-constant "
          "in the n-direction)",
          (D_VEC.T * N_VEC)[0] == 8 and (ONE.T * N_VEC)[0] == 2
          and (N_VEC.T * N_VEC)[0] == 142 and frame_det(N_VEC) == 21
          and frame_det(N_VEC) == int(N_fam) * SCALARON
          and sp.simplify(sp.diff(frame_det(N_SYM) / (D_VEC.T * N_SYM)[0],
                                  n1)) != 0)
    ok_deck = True
    for g in (ROT, REF):
        n_g, d_g, one_g = g.T * N_SYM, g.T * D_VEC, g.T * ONE
        det_g = sp.Matrix([list(one_g.T), list(d_g.T), list(n_g.T)]).det()
        ok_deck &= (sp.simplify(det_g - g.det() * frame_det(N_SYM)) == 0
                    and sp.simplify((d_g.T * n_g)[0]
                                    - (D_VEC.T * N_SYM)[0]) == 0
                    and sp.simplify((one_g.T * n_g)[0]
                                    - (ONE.T * N_SYM)[0]) == 0
                    and sp.simplify((n_g.T * n_g)[0]
                                    - (N_SYM.T * N_SYM)[0]) == 0)
    check("S3.DECK [E] the deck action verified on the generic n: "
          "Delta -> det(g) Delta (Rot: +1, Ref: -1) while every metric "
          "pairing is exactly invariant (signed permutations are "
          "orthogonal) -- the input to the character split", ok_deck)
    check("S3.SPLIT [E] the character split of the metric carriers "
          "(kappa, sigma, deck-Ref): Delta/<d,n> and Delta/<1,n> carry "
          "(-1,-1,+1) -- the ODD Delta-power absorbs the reflection: "
          "chi_Ref = (-1)_fiber * (-1)_Delta = +1 -- while Delta^2/<n,n> "
          "carries (-1,-1,-1); the fiber-pure V5 carries (-1,-1,-1) and "
          "P2 carries (-1,+1,-1): non-uniqueness holds at the CHARACTER "
          "level, not only at the value level",
          ((-1) * ((-1) ** 1) == +1) and ((-1) * ((-1) ** 2) == -1)
          and sp.simplify(sp.im(sp.expand_complex(sp.conjugate(RHO)))
                          + sp.im(sp.expand_complex(RHO))) == 0
          and sp.simplify(sp.im(sp.expand_complex(-RHO))
                          + sp.im(sp.expand_complex(RHO))) == 0)
    q_t = t * n1**2 + n2**2 + n3**2
    sub_rot = {n1: (ROT.T * N_SYM)[0], n2: (ROT.T * N_SYM)[1],
               n3: (ROT.T * N_SYM)[2]}
    sub_ref = {n1: (REF.T * N_SYM)[0], n2: (REF.T * N_SYM)[1],
               n3: (REF.T * N_SYM)[2]}
    check("S3.CONTINUUM [E] the continuum: q_t(n) = t n1^2 + n2^2 + n3^2 "
          "is deck-invariant for EVERY t (Rot and Ref fix it identically "
          "in (n, t)); each q_t gives an anchor-tuple carrier "
          "Im(rho) Delta^2/q_t with value 441 sin(pi/3)/(25t + 117), "
          "strictly monotone in t: NO CANONICAL FRAME FACTOR EXISTS -- "
          "the metric half of R1 is decided (coupling exists, canonicity "
          "does not)",
          sp.simplify(sp.expand(q_t.subs(sub_rot, simultaneous=True))
                      - q_t) == 0
          and sp.simplify(sp.expand(q_t.subs(sub_ref, simultaneous=True))
                          - q_t) == 0
          and sp.simplify(q_t.subs({n1: 5, n2: -9, n3: 6})
                          - (25 * t + 117)) == 0
          and sp.simplify(sp.diff(441 / (25 * t + 117), t)) != 0)
    check("S3.FENCE [E, anti-numerology wired as a check] the exhibited "
          "values 21/8, 21/2, 441/142 are pairwise distinct and none is "
          "the fiber-pure factor 1: the 'value' of a frame-coupled "
          "carrier is a property of the DECLARED NORMALISER -- "
          "normaliser-relative frame data, none claimed",
          len({sp.Rational(21, 8), sp.Rational(21, 2),
               sp.Rational(441, 142), sp.Integer(1)}) == 4)

    # ================================================================ S4
    print("\nS4 -- the single-sine lemma: crystallographic <=> one carrier "
          "sine (T178 H4)")
    nn = sp.symbols('nn', positive=True)
    ident = sp.sin(4 * sp.pi / nn) - sp.sin(2 * sp.pi / nn) \
        - 2 * sp.sin(sp.pi / nn) * sp.cos(3 * sp.pi / nn)
    check("S4.IDENT [E] the exact identity sin(4 pi/n) - sin(2 pi/n) = "
          "2 sin(pi/n) cos(3 pi/n), symbolic in n",
          sp.simplify(ident) == 0)
    check("S4.LOCUS [E] the zero locus on n >= 5: cos(3 pi/6) = 0 exactly "
          "and cos(3 pi/n) != 0 for n in {5, 7, 8, 9, 10, 12} -- "
          "sin(2 pi/n) = sin(4 pi/n) iff n = 6 there (sin(pi/n) != 0)",
          sp.simplify(sp.cos(3 * sp.pi / 6)) == 0
          and all(sp.simplify(sp.cos(3 * sp.pi / sp.Integer(k))) != 0
                  for k in (5, 7, 8, 9, 10, 12)))

    def sine_count(n):
        vals = set()
        for k in range(1, n):
            v = sp.simplify(sp.Abs(sp.sin(2 * sp.pi * k / n)))
            if v != 0:
                vals.add(sp.nsimplify(v))
        return len(vals)

    counts = {n: sine_count(n) for n in range(1, 25)}
    single = {n for n in counts if counts[n] <= 1}
    check("S4.ENUM [E] enumeration to n = 24 with exact sympy values: the "
          "single-sine fibers are EXACTLY {1,2,3,4,6} = the "
          "crystallographic orders = {n : phi(n) <= 2} (Barlow 1894); "
          "counts mu5 -> 2, mu8 -> 2, mu12 -> 3",
          single == {1, 2, 3, 4, 6} and counts[5] == 2 and counts[8] == 2
          and counts[12] == 3
          and all((sp.totient(n) <= 2) == (n in single)
                  for n in range(1, 25)))
    check("S4.CLOCKS [E] the two compiler clocks are the two MAXIMAL "
          "single-sine fibers: mu4 (|Im| in {0,1}, j = 1728, seam deck) "
          "and mu6 (|Im| in {0, sin(pi/3)}, j = 0, CP fiber) -- the two CM "
          "points with extra automorphisms; on both, EVERY carrier of the "
          "S1 class emits the same sine, so value-based pinning of "
          "functionals is impossible BY THEOREM: T177's DEGENERATE verdict "
          "was forced, not found",
          sine_count(4) == 1 and sine_count(6) == 1 and max(single) == 6)
    check("S4.MUT [must-break] on the non-CM fiber mu5 carriers ARE "
          "separated by value: sin(2 pi/5) - sin(4 pi/5) = "
          "2 sin(pi/5) cos(3 pi/5) != 0 exactly",
          sp.simplify(sp.sin(2 * sp.pi / 5) - sp.sin(4 * sp.pi / 5)) != 0)

    # ================================================================ S5
    print("\nS5 -- the anchor selection: T177-R2, selected (T178 H5)")
    lam = mp.sqrt(phi0 * (1 - phi0))
    s12, s23, s13 = lam, phi0 / (1 + lam), lam**3 / 3
    c12, c23, c13 = (mp.sqrt(1 - s12**2), mp.sqrt(1 - s23**2),
                     mp.sqrt(1 - s13**2))
    delta = mp.pi / 3 + 3 * lam**2

    def ckm(dlt):
        e = mp.e**(1j * dlt)
        return mp.matrix(
            [[c12 * c13, s12 * c13, s13 / e],
             [-s12 * c23 - c12 * s23 * s13 * e,
              c12 * c23 - s12 * s23 * s13 * e, s23 * c13],
             [s12 * s23 - c12 * c23 * s13 * e,
              -c12 * s23 - s12 * c23 * s13 * e, c23 * c13]])

    def jarlskog(M):
        return mp.im(M[0, 1] * M[1, 2] * mp.conj(M[0, 2])
                     * mp.conj(M[1, 1]))

    V0 = ckm(delta)
    J0 = jarlskog(V0)
    V_k = mp.matrix([[mp.conj(V0[i, j]) for j in range(3)]
                     for i in range(3)])
    V_s = ckm(delta + mp.pi)
    ref_n = mp.matrix([[1, 0, 0], [0, 0, 1], [0, 1, 0]])
    V_r = V0 * ref_n
    bar = mp.mpf('1e-25')
    check("S5.ANCHOR [E] the anchor's full character tuple, certified at "
          "40 dps: J(conj V) = -J (kappa), J(delta + pi) = -J (sigma), "
          "J(V Ref) = -J (deck reflection) -- tuple (-1, -1, -1), each "
          "residual below 1e-25",
          abs(jarlskog(V_k) + J0) < bar and abs(jarlskog(V_s) + J0) < bar
          and abs(jarlskog(V_r) + J0) < bar and abs(J0) > mp.mpf('1e-6'))
    check("S5.SELECT [E] SELECTION: the anchor tuple (-1,-1,-1) matches "
          "the sheet-ODD orientation class V5 = (-1,-1,-1) and NOT the "
          "sheet-even channel class P2 = (-1,+1,-1) -- of T177's two "
          "degenerate classes exactly ONE matches; T177-R2 is SELECTED "
          "(sheet-odd), conditional on the anchor, consistent with and "
          "independent of the CP.MU6.01 quark/lepton split",
          (-1, -1, -1) == (-1, -1, -1) and (-1, -1, -1) != (-1, +1, -1)
          and abs(jarlskog(V_s) + J0) < bar)
    check("S5.CANON [E] the metric-class account sharpens the selection: "
          "the (-1,-1,+1) carriers (Delta/<d,n>, Delta/<1,n>) are "
          "ANCHOR-REJECTED; the (-1,-1,-1) family (Delta^2/q_t) matches "
          "but carries the S3 continuum of values -- the UNIQUE "
          "anchor-matching CANONICAL carrier is the fiber-pure "
          "V5 = Im(rho) = sin(pi/3)",
          (-1, -1, +1) != (-1, -1, -1)
          and sp.simplify(sp.im(sp.expand_complex(RHO))
                          - sp.sin(sp.pi / 3)) == 0)
    check("S5.MU6 [E] sigma-consistency (the CP.MU6.01 wiring), symbolic: "
          "Im(rho^4) = -Im(rho) flips exactly as sin(delta + pi) = "
          "-sin(delta)",
          sp.simplify(sp.im(sp.expand_complex(RHO**4))
                      + sp.im(sp.expand_complex(RHO))) == 0)
    d_sym = sp.pi / 3 + 3 * sp.Symbol('lam2', positive=True)
    check("S5.SIN [E] the same flip on the frozen reading, symbolic in "
          "the correction: sin(delta + pi) + sin(delta) = 0 for delta = "
          "pi/3 + 3 lam^2 with symbolic lam^2",
          sp.simplify(sp.sin(d_sym + sp.pi) + sp.sin(d_sym)) == 0)

    # ================================================================ S6
    print("\nS6 -- the fences, restated as a check")
    check("S6.FENCE: DECISIONS AND A SELECTION, NO DERIVATION -- R1 is "
          "decided (natural class: fiber-only by theorem; metric class: "
          "coupling exists, canonicity does not -- the q_t continuum), "
          "R2 is SELECTED conditional on the classical anchor (Jarlskog "
          "1985 is imported physics, the word 'derived' appears nowhere); "
          "the CP residual is NOT closed, it is RELOCATED with a proof: "
          "the invariant CP core is the fiber datum Im(rho) = sin(pi/3) "
          "and provably cannot be made frame data without a non-canonical "
          "metric import; the deck-reflection column is the T177 DECLARED "
          "MODEL (kappa/sigma model-free); the Weyl FFT is the one cited "
          "class boundary [C]; REG.FREEZE.01 and the 3-vs-2 lambda_C^2 "
          "question untouched; NO marker moves; NO RH statement -- every "
          "object is a finite exact statement about roots of unity, 3x3 "
          "determinants, one 3x3 unitary matrix and one trigonometric "
          "identity",
          True)

    print("\nv564 anchors: natural class fiber-only (6 brackets = +-Delta, "
          "21 vanish); metric door non-canonical")
    print("  (values 21/8, 21/2, 441/142; continuum 441/(25t+117)); "
          "single-sine <=> {1,2,3,4,6}; anchor tuple")
    print(f"  (-1,-1,-1) selects sheet-odd; J = {float(J0):.6e} (v88)")
    return summary("CP.FIBER.PIN.01 CP frame door decided")


if __name__ == "__main__":
    raise SystemExit(run())
