"""Exact finite composition data for the covariant TFPT trimer branch.

The calculation joins two fixed conjugate trimer blocks.  It determines the
leakage-free positive nine-pair bridge inside the stated operator class; it
does not claim that the primitive TFPT source selects this interaction.
"""

from __future__ import annotations

from collections import Counter
from functools import lru_cache
import itertools as it
import math
from typing import Any

import numpy as np
import sympy as sp

from .consolidation import TRIMERS, _covariant_chain, _periodic_voltage_data
from .process import _invariants


DIMENSION = 5
OPPOSITE_EDGES = ((0, 3), (0, 5), (2, 3), (2, 5), (1, 4))
SAME_EDGES = ((0, 4), (2, 4), (1, 3), (1, 5))
LEAKAGE_DENOMINATOR = 8640


def _check(name: str, ok: bool, actual: Any, expected: Any, method: str) -> dict[str, Any]:
    return {
        "name": name,
        "ok": bool(ok),
        "actual": actual,
        "expected": expected,
        "method": method,
    }


def _swap() -> np.ndarray:
    result = np.zeros((25, 25), dtype=np.int64)
    for left, right in it.product(range(DIMENSION), repeat=2):
        result[right * DIMENSION + left, left * DIMENSION + right] = 1
    return result


def _apply_pair(
    operator: np.ndarray,
    left: int,
    right: int,
    states: np.ndarray,
) -> np.ndarray:
    """Apply a two-site operator without forming a 5^6 square matrix."""

    tensor = states.reshape((DIMENSION,) * 6 + (states.shape[1],))
    order = (left, right) + tuple(
        site for site in range(6) if site not in (left, right)
    ) + (6,)
    inverse = np.argsort(order)
    leading = np.transpose(tensor, order).reshape(25, -1)
    transformed = operator @ leading
    return np.transpose(
        transformed.reshape((DIMENSION,) * 6 + (states.shape[1],)), inverse
    ).reshape(DIMENSION**6, states.shape[1])


def _su_generators() -> list[np.ndarray]:
    """Hermitian traceless basis normalised by tr(t_a t_b)=delta_ab."""

    generators: list[np.ndarray] = []
    for left, right in it.combinations(range(DIMENSION), 2):
        symmetric = np.zeros((DIMENSION, DIMENSION), dtype=complex)
        symmetric[left, right] = symmetric[right, left] = 1 / np.sqrt(2)
        antisymmetric = np.zeros((DIMENSION, DIMENSION), dtype=complex)
        antisymmetric[left, right] = -1j / np.sqrt(2)
        antisymmetric[right, left] = 1j / np.sqrt(2)
        generators.extend((symmetric, antisymmetric))
    for index in range(1, DIMENSION):
        diagonal = np.zeros((DIMENSION, DIMENSION), dtype=complex)
        diagonal[range(index), range(index)] = 1
        diagonal[index, index] = -index
        generators.append(diagonal / np.sqrt(index * (index + 1)))
    return generators


def _exact_remainder_orbit_certificate() -> dict[str, Any]:
    """Certify the SU(5) module generated by R without float reconstruction.

    In the source normalisation ``sqrt(96) R = 12 T + 2 D - 4 N_W``.
    The simplex, T, D and the integer W numerator are built here over the
    exact algebraic field Q(sqrt(2), sqrt(3)).  Acting with all 25 matrix
    units is equivalent to adjoining R and the 24 traceless directions.
    """

    simplex = (
        (1 / (2 * sp.sqrt(3)), -sp.Rational(1, 2), -sp.Rational(1, 2), -sp.Rational(1, 2), 0),
        (1 / (2 * sp.sqrt(3)), -sp.Rational(1, 2), sp.Rational(1, 2), sp.Rational(1, 2), 0),
        (1 / (2 * sp.sqrt(3)), sp.Rational(1, 2), -sp.Rational(1, 2), sp.Rational(1, 2), 0),
        (1 / (2 * sp.sqrt(3)), sp.Rational(1, 2), sp.Rational(1, 2), -sp.Rational(1, 2), 0),
        (-1 / sp.sqrt(3), 0, 0, 0, 1 / sp.sqrt(2)),
        (-1 / sp.sqrt(3), 0, 0, 0, -1 / sp.sqrt(2)),
    )
    remainder_entries: dict[tuple[int, int], sp.Expr] = {}
    w_entries: dict[tuple[int, int], int] = {}
    remainder_tensor: dict[tuple[int, int, int, int], sp.Expr] = {}
    symmetric = True
    for a, b, c, x in it.product(range(5), repeat=4):
        tensor_t = sum(row[a] * row[b] * row[c] * row[x] for row in simplex)
        tensor_d = int(a == b and c == x) + int(a == c and b == x) + int(a == x and b == c)
        w_numerator = int(a == b and c == x) + int(a == x and b == c)
        value = sp.simplify(12 * tensor_t + 2 * tensor_d - 4 * w_numerator)
        row_index = 25 * a + 5 * b + c
        if value != 0:
            remainder_entries[(row_index, x)] = value
            remainder_tensor[(a, b, c, x)] = value
        if w_numerator:
            w_entries[(row_index, x)] = w_numerator
    for a, b, c, x in it.product(range(5), repeat=4):
        symmetric &= sp.simplify(
            remainder_tensor.get((a, b, c, x), 0)
            - remainder_tensor.get((c, b, a, x), 0)
        ) == 0

    remainder_exact = sp.MutableSparseMatrix(125, 5, remainder_entries)
    w_exact = sp.MutableSparseMatrix(125, 5, w_entries)
    orbit_entries: dict[tuple[int, int], sp.Expr] = {}
    for i, j, x in it.product(range(5), repeat=3):
        column = 25 * i + 5 * j + x
        for a, b, c in it.product(range(5), repeat=3):
            value = 0
            if a == i:
                value += remainder_tensor.get((j, b, c, x), 0)
            if b == j:
                value -= remainder_tensor.get((a, i, c, x), 0)
            if c == i:
                value += remainder_tensor.get((a, b, j, x), 0)
            value = sp.simplify(value)
            if value != 0:
                orbit_entries[(25 * a + 5 * b + c, column)] = value
    orbit = sp.MutableSparseMatrix(125, 125, orbit_entries)
    orbit_rank = int(orbit.rank())
    joint_rank = int(sp.Matrix.hstack(w_exact, orbit).rank())
    return {
        "remainder_scale": "sqrt(96) R=12T+2D-4N_W",
        "remainder_gram_exact": remainder_exact.T * remainder_exact == 96 * sp.eye(5),
        "w_orthogonality_exact": w_exact.T * remainder_exact == sp.zeros(5),
        "outer_symmetry_exact": bool(symmetric),
        "orbit_rank": orbit_rank,
        "w_plus_orbit_rank": joint_rank,
    }


def _primitive_integer_ray(vector: sp.Matrix) -> list[int]:
    denominator = math.lcm(*(int(value.q) for value in vector))
    values = [int(value * denominator) for value in vector]
    divisor = math.gcd(*values)
    values = [value // divisor for value in values]
    if sum(values) < 0:
        values = [-value for value in values]
    return values


def _exact_bridge(
    block_integer: np.ndarray,
    term_rows: list[tuple[str, tuple[int, int], np.ndarray]],
) -> dict[str, Any]:
    leakage_numerators = []
    projected_numerators = []
    for kind, edge, operator in term_rows:
        applied = _apply_pair(operator, *edge, block_integer)
        projected = block_integer.T @ applied
        leakage = 144 * applied - block_integer @ projected
        if kind == "same":
            leakage *= 5
        leakage_numerators.append(leakage.reshape(-1))
        projected_numerators.append(projected)

    leakage_integer = np.column_stack(leakage_numerators)
    gram_numerator = leakage_integer.T @ leakage_integer
    gram = sp.Matrix(gram_numerator) / LEAKAGE_DENOMINATOR**2
    nullspace = gram.nullspace()
    integer_ray = _primitive_integer_ray(nullspace[0]) if len(nullspace) == 1 else []
    return {
        "gram": gram,
        "integer_ray": integer_ray,
        "projected_sum": sum(
            projected_numerators, np.zeros((25, 25), dtype=np.int64)
        ),
    }


def _coarse_a3_data() -> dict[str, Any]:
    invariants = _invariants()
    periodic = _periodic_voltage_data()
    node_data: dict[int, dict[str, Any]] = {}
    blocks = []
    for block, (center, left, right, left_shift, right_shift, representation) in enumerate(TRIMERS):
        blocks.append(
            {
                "id": block,
                "center": center,
                "constituents": [left, center, right],
                "representation": representation,
            }
        )
        node_data[center] = {
            "block": block,
            "role": "middle",
            "representation": representation,
            "offset": (0, 0, 0),
        }
        for leaf, offset in ((left, left_shift), (right, right_shift)):
            node_data[leaf] = {
                "block": block,
                "role": "end",
                "representation": representation,
                "offset": offset,
            }

    graph_edges = [
        (int(matching[1:]), 15 + int(pair[1:]))
        for matching, pair in invariants["geometry_edges"]
    ]
    strong_edges = {
        tuple(sorted((center, leaf)))
        for center, left, right, *_rest in TRIMERS
        for leaf in (left, right)
    }
    coarse_edges = []
    for matching, pair in graph_edges:
        if tuple(sorted((matching, pair))) in strong_edges:
            continue
        left = node_data[matching]
        right = node_data[pair]
        coarse_edges.append(
            {
                "source": left["block"],
                "target": right["block"],
                "microscopic_edge": [matching, pair],
                "source_role": left["role"],
                "target_role": right["role"],
                "source_representation": left["representation"],
                "target_representation": right["representation"],
                "orientation": (
                    "opposite"
                    if left["representation"] != right["representation"]
                    else "same"
                ),
                "microscopic_period": list(periodic["voltages"][(matching, pair)]),
                "period": [int(v + a - b) for v, a, b in zip(
                    periodic["voltages"][(matching, pair)], left["offset"], right["offset"]
                )],
            }
        )

    degrees = Counter()
    for edge in coarse_edges:
        degrees[edge["source"]] += 1
        degrees[edge["target"]] += 1
    orientations = Counter(edge["orientation"] for edge in coarse_edges)
    role_pairs = Counter(
        (edge["source_role"], edge["target_role"]) for edge in coarse_edges
    )
    return {
        "blocks": blocks,
        "edges": coarse_edges,
        "edge_count": len(coarse_edges),
        "degree_sequence": [degrees[index] for index in range(len(blocks))],
        "orientation_counts": dict(orientations),
        "role_pair_counts": {
            f"{left}-{right}": count for (left, right), count in role_pairs.items()
        },
        "single_link_projection": {
            "end-end": {"coefficient": "49/144", "constant": "19/36", "operator": "h_opp"},
            "middle-end": {"coefficient": "-7/72", "constant": "59/72", "operator": "h_same"},
            "scope": "Compression of each original weak h_opp edge; not an invariant-block identity and not the nine-port completion.",
        },
    }


@lru_cache(maxsize=1)
def build_joint_data() -> dict[str, Any]:
    """Return JSON-serialisable exact bridge data and its checks."""

    invariants = _invariants()
    chain = _covariant_chain()
    w = chain["w"].astype(float)
    # Build an integer certificate directly from the defining Kronecker deltas.
    w_integer = np.zeros((125, 5), dtype=np.int64)
    for a, b, c, x in it.product(range(5), repeat=4):
        w_integer[25 * a + 5 * b + c, x] = int(a == b and c == x) + int(a == x and b == c)
    block_integer = np.kron(w_integer, w_integer)
    block_isometry_exact = np.array_equal(
        block_integer.T @ block_integer, 144 * np.eye(25, dtype=np.int64)
    )

    identity = np.eye(25, dtype=np.int64)
    identity_vector = np.eye(5, dtype=np.int64).reshape(-1)
    singlet_numerator = np.outer(identity_vector, identity_vector)
    opposite_integer = 5 * identity - singlet_numerator
    same_integer = identity + _swap()

    conjugate_rows = [
        ("opposite", edge, opposite_integer) for edge in OPPOSITE_EDGES
    ] + [("same", edge, same_integer) for edge in SAME_EDGES]
    conjugate_bridge = _exact_bridge(block_integer, conjugate_rows)
    exact_gram = conjugate_bridge["gram"]
    opposite_gram = exact_gram[:5, :5]
    null_weights = conjugate_bridge["integer_ray"]
    expected_weights = [5] * 5 + [1] * 4

    # The physical positive terms are h_opp=O_opp/6 and h_same=O_same/6.
    # In the raw bases (I-P_Omega, I+Swap), this is the 5:1 null ray.
    projected_target = 4176 * identity - 144 * singlet_numerator
    projected_exact = np.array_equal(
        conjugate_bridge["projected_sum"], projected_target
    )

    same_rows = [("same", edge, same_integer) for edge in OPPOSITE_EDGES] + [
        ("opposite", edge, opposite_integer) for edge in SAME_EDGES
    ]
    same_bridge = _exact_bridge(block_integer, same_rows)
    same_gram = same_bridge["gram"]
    same_weights = same_bridge["integer_ray"]
    expected_same_weights = [1] * 5 + [5] * 4
    same_projected_target = 3600 * identity + 144 * _swap()
    same_projected_exact = np.array_equal(
        same_bridge["projected_sum"], same_projected_target
    )

    generators = _su_generators()
    swap = _swap().astype(complex)
    identity_complex = np.eye(25, dtype=complex)
    singlet = singlet_numerator.astype(float) / 5
    same_complete = sum(
        (np.kron(generator, generator) for generator in generators),
        np.zeros((25, 25), dtype=complex),
    )
    opposite_complete = sum(
        (np.kron(generator, -generator.T) for generator in generators),
        np.zeros((25, 25), dtype=complex),
    )
    same_complete_error = float(
        np.linalg.norm(same_complete - (swap - identity_complex / 5))
    )
    opposite_complete_error = float(
        np.linalg.norm(opposite_complete - (-5 * singlet + identity_complex / 5))
    )

    h_cov = (5 / 6) * (np.eye(25) - singlet)
    projected_bridge = 4 * np.eye(25) + h_cov
    hypercharge = np.diag([-1 / 3] * 3 + [1 / 2] * 2)
    effective_charge = np.kron(hypercharge, np.eye(5)) - np.kron(
        np.eye(5), hypercharge.T
    )
    charge_error = float(
        np.linalg.norm(projected_bridge @ effective_charge - effective_charge @ projected_bridge)
    )

    g_encoder = invariants["v_triangle"]
    overlap_error = float(
        np.linalg.norm(w.T @ g_encoder - np.sqrt(2 / 3) * np.eye(5))
    )
    remainder = (g_encoder - np.sqrt(2 / 3) * w) / np.sqrt(1 / 3)
    remainder_isometry_error = float(np.linalg.norm(remainder.T @ remainder - np.eye(5)))
    remainder_orthogonality_error = float(np.linalg.norm(w.T @ remainder))
    remainder_energy_error = float(
        np.linalg.norm(chain["chain"] @ remainder - (5 / 3) * remainder)
    )
    event_error = max(
        float(np.linalg.norm(np.kron(np.kron(event, event), event) @ w - w @ event))
        for event in invariants["transpositions"]
    )

    # The source encoder has support on exactly two H_path eigenspaces.  Check
    # its analytic return law against the native 125x125 spectral evolution.
    chain_eigenvalues, chain_eigenvectors = np.linalg.eigh(chain["chain"])
    path_projectors = {}
    path_weights = {}
    for label, energy, expected_weight in (
        ("W", 2 / 3, 2 / 3),
        ("R", 5 / 3, 1 / 3),
    ):
        eigenspace = chain_eigenvectors[:, np.isclose(chain_eigenvalues, energy, atol=1e-12)]
        projector = eigenspace @ eigenspace.T.conj()
        path_projectors[label] = projector
        weight = g_encoder.T.conj() @ projector @ g_encoder
        path_weights[label] = {
            "energy": str(sp.Rational(energy).limit_denominator()),
            "weight": str(sp.Rational(expected_weight).limit_denominator()),
            "matrix_residual": float(np.linalg.norm(weight - expected_weight * np.eye(5))),
        }
    other_spectral_weight = float(
        np.linalg.norm(
            g_encoder.T.conj()
            @ (np.eye(125) - path_projectors["W"] - path_projectors["R"])
            @ g_encoder
        )
    )
    return_samples = []
    return_error = 0.0
    for time in (0.0, math.pi / 3, math.pi / 2, math.pi, 2 * math.pi):
        evolution = (
            chain_eigenvectors * np.exp(-1j * time * chain_eigenvalues)
        ) @ chain_eigenvectors.T.conj()
        amplitude_matrix = g_encoder.T.conj() @ evolution @ g_encoder
        analytic_amplitude = (
            (2 / 3) * np.exp(-2j * time / 3)
            + (1 / 3) * np.exp(-5j * time / 3)
        )
        analytic_probability = (5 + 4 * math.cos(time)) / 9
        direct_probability = float(
            np.real(np.trace(amplitude_matrix.T.conj() @ amplitude_matrix)) / 5
        )
        amplitude_residual = float(
            np.linalg.norm(amplitude_matrix - analytic_amplitude * np.eye(5))
        )
        return_error = max(
            return_error,
            amplitude_residual,
            abs(direct_probability - analytic_probability),
        )
        return_samples.append(
            {
                "time_over_pi": str(sp.Rational(time / math.pi).limit_denominator()),
                "direct_probability": direct_probability,
                "formula_probability": analytic_probability,
                "amplitude_matrix_residual": amplitude_residual,
            }
        )

    carry = np.concatenate((w, remainder), axis=1).astype(complex)
    carry_effective = np.diag([2 / 3] * 5 + [5 / 3] * 5)
    carry_path_residual = float(
        np.linalg.norm(chain["chain"] @ carry - carry @ carry_effective)
    )
    carry_projector = carry @ carry.T.conj()
    generator_leakages = []
    physical_identity = np.eye(5)
    for generator in generators:
        collective = (
            np.kron(np.kron(generator, physical_identity), physical_identity)
            - np.kron(np.kron(physical_identity, generator.T), physical_identity)
            + np.kron(np.kron(physical_identity, physical_identity), generator)
        )
        generator_leakages.append(
            float(np.linalg.norm((np.eye(125) - carry_projector) @ collective @ carry))
        )
    exact_orbit = _exact_remainder_orbit_certificate()

    coarse = _coarse_a3_data()
    leaf_projection = block_integer.T @ _apply_pair(opposite_integer, 0, 3, block_integer)
    center_projection = block_integer.T @ _apply_pair(opposite_integer, 0, 4, block_integer)
    single_links_exact = (
        np.array_equal(leaf_projection, 701 * identity - 49 * singlet_numerator)
        and np.array_equal(center_projection, 694 * identity - 14 * _swap())
    )
    checks = [
        _check("Reale Einzel-Restlinks erzeugen beide effektiven Bindungen", single_links_exact,
               bool(single_links_exact), True,
               "Exakte Integerkompression /864: Blatt–Blatt=(701I−49|I><I|)/864; Mitte–Blatt=(694I−14Swap)/864"),
        _check(
            "Ganzzahliger Zweiblock-Encoder ist exakt isometrisch",
            block_isometry_exact,
            bool(block_isometry_exact),
            True,
            "N^T N=144 I für V=(W tensor Wbar)=N/12",
        ),
        _check(
            "Nur fünf Gegenorientierungs-Paare schließen nicht",
            opposite_gram.rank() == 5 and opposite_gram.det() == sp.Rational(67228, 273375),
            {"rank": opposite_gram.rank(), "determinant": str(opposite_gram.det())},
            {"rank": 5, "determinant": "67228/273375"},
            "exakte ganzzahlige Leakage-Gramdeterminante",
        ),
        _check(
            "Neun-Paar-Klasse hat genau einen Nullstrahl",
            exact_gram.rank() == 8 and null_weights == expected_weights,
            {"rank": exact_gram.rank(), "weights": null_weights},
            {"rank": 8, "weights": [5, 5, 5, 5, 5, 1, 1, 1, 1]},
            "exakter Nullraum des 9x9 Leakage-Gram",
        ),
        _check(
            "Positive Brücke schließt exakt auf 4I+h_cov",
            projected_exact,
            bool(projected_exact),
            True,
            "ganzzahlige Identität sum B=4176 I-144 |I><I|",
        ),
        _check(
            "Gleichorientierte Neun-Paar-Klasse schließt eindeutig",
            same_gram.rank() == 8
            and same_weights == expected_same_weights
            and same_projected_exact,
            {
                "rank": same_gram.rank(),
                "weights": same_weights,
                "projected": bool(same_projected_exact),
            },
            {
                "rank": 8,
                "weights": [1, 1, 1, 1, 1, 5, 5, 5, 5],
                "projected": True,
            },
            "exakter Nullraum und V^T H9 V=4I+h_same",
        ),
        _check(
            "Generatorvollständigkeit liefert fünf Singulett- und vier Swap-Terme",
            max(same_complete_error, opposite_complete_error) < 2e-14,
            {"same": same_complete_error, "opposite": opposite_complete_error},
            {"same": 0, "opposite": 0},
            "24 orthonormale su(5)-Generatoren, Toleranz 2e-14",
        ),
        _check(
            "Projizierte Brücke erhält die 3+2-Ladung",
            charge_error < 1e-14,
            charge_error,
            0,
            "Kommutator mit Y tensor I-I tensor Y^T",
        ),
        _check(
            "G-Tensor zerfällt gleichmäßig in W und orthogonalen 5/3-Sektor",
            max(overlap_error, remainder_isometry_error, remainder_orthogonality_error, remainder_energy_error) < 1e-12,
            {
                "overlap": overlap_error,
                "remainder_isometry": remainder_isometry_error,
                "orthogonality": remainder_orthogonality_error,
                "remainder_energy": remainder_energy_error,
            },
            0,
            "V_G=sqrt(2/3)W+sqrt(1/3)R und H_path R=(5/3)R",
        ),
        _check(
            "Nativer Pfadclock liefert die analytische Quellenrückkehr",
            max(
                return_error,
                other_spectral_weight,
                carry_path_residual,
                *(entry["matrix_residual"] for entry in path_weights.values()),
            ) < 1e-12,
            {
                "return_residual": return_error,
                "other_spectral_weight": other_spectral_weight,
                "carry_residual": carry_path_residual,
            },
            0,
            "direkte Spektralmatrix: V_G^dag exp(-it H_path)V_G gegen [(2/3)e^(-2it/3)+(1/3)e^(-5it/3)]I5",
        ),
        _check(
            "R erzeugt exakt den 70-dimensionalen Ladungsabschluss",
            exact_orbit["remainder_gram_exact"]
            and exact_orbit["w_orthogonality_exact"]
            and exact_orbit["outer_symmetry_exact"]
            and exact_orbit["orbit_rank"] == 70
            and exact_orbit["w_plus_orbit_rank"] == 75
            and min(generator_leakages) > 1,
            {
                "orbit_rank": exact_orbit["orbit_rank"],
                "with_W": exact_orbit["w_plus_orbit_rank"],
                "minimum_carry_leakage": min(generator_leakages),
            },
            {"orbit_rank": 70, "with_W": 75, "carry_closed_under_full_su5": False},
            "exakter Q(sqrt(2),sqrt(3))-Rang der 25 Matrixeinheitswirkungen; direkte Leakage aller 24 orthonormalen su(5)-Generatoren",
        ),
        _check(
            "Alle 15 Quellenereignisse intertwinen mit W",
            event_error < 1e-12,
            event_error,
            0,
            "max ||T_a^tensor3 W-WT_a||, Toleranz 1e-12",
        ),
        _check(
            "Jeder vervollständigte Link reduziert jeden Blockraum",
            chain["covariance_error"] < 1e-12,
            chain["covariance_error"],
            0,
            "(X1-X2^T+X3)W=WX für alle 25 Matrixeinheiten; daraus [H_ij,P_i]=[H_ij,P_j]=0",
        ),
        _check(
            "A3-Cover ergibt einen einfachen fünffach regulären Zehnblockgraphen",
            coarse["edge_count"] == 25
            and len({tuple(sorted((edge["source"], edge["target"]))) for edge in coarse["edges"]}) == 25
            and coarse["degree_sequence"] == [5] * 10
            and coarse["orientation_counts"] == {"same": 10, "opposite": 15},
            {
                "edges": coarse["edge_count"],
                "degrees": coarse["degree_sequence"],
                "orientations": coarse["orientation_counts"],
            },
            {"edges": 25, "degrees": [5] * 10, "orientations": {"same": 10, "opposite": 15}},
            "direkte Kontraktion der 20 starken Kanten aus dem 45-Kanten-Netz",
        ),
    ]

    data = {
        "scope": (
            "exact finite result for the named positive nine-pair class and the "
            "given W/Wbar blocks; no primitive source selection, global-ground-state "
            "selection, physical-generator identification, or continuum claim"
        ),
        "block_shape": [DIMENSION**6, 25],
        "positive_pair_class": {
            "opposite_edges": [list(edge) for edge in OPPOSITE_EDGES],
            "same_edges": [list(edge) for edge in SAME_EDGES],
            "opposite_term": "h_opp=(5/6)(I-P_Omega)",
            "same_term": "h_same=(1/6)(I+Swap)",
        },
        "leakage": {
            "common_denominator": LEAKAGE_DENOMINATOR,
            "opposite_rank": int(opposite_gram.rank()),
            "opposite_determinant": str(opposite_gram.det()),
            "full_rank": int(exact_gram.rank()),
            "full_nullity": 9 - int(exact_gram.rank()),
            "unique_raw_weights": null_weights,
            "exact_gram": [
                [str(exact_gram[row, column]) for column in range(9)]
                for row in range(9)
            ],
            "same_orientation": {
                "term_order": "five same, then four opposite",
                "full_rank": int(same_gram.rank()),
                "full_nullity": 9 - int(same_gram.rank()),
                "unique_raw_weights": same_weights,
                "exact_gram": [
                    [str(same_gram[row, column]) for column in range(9)]
                    for row in range(9)
                ],
            },
        },
        "bridge": {
            "microscopic_identity": (
                "H_bridge=(24/5)I+(1/6)sum_a Q_A^a Q_B^a"
            ),
            "projected_identity": "V^T H_bridge V=4I+h_cov",
            "projected_spectrum": [
                {"value": "4", "multiplicity": 1},
                {"value": "29/6", "multiplicity": 24},
            ],
            "constant_per_bridge": "4",
            "charge_commutator_residual": charge_error,
            "same_orientation": {
                "microscopic_identity": (
                    "H_bridge_same=(21/5)I+(1/6)sum_a Q_A^a Q_B^a"
                ),
                "projected_identity": "V^T H_bridge_same V=4I+h_same",
                "projected_spectrum": [
                    {"value": "4", "multiplicity": 10},
                    {"value": "13/3", "multiplicity": 15},
                ],
            },
            "clock_scope": (
                "SU(5)-covariant on the code five-space, hence compatible with "
                "its C4 action; it does not identify the distinct RR five-space clock"
            ),
        },
        "quartic_to_path": {
            "identity": "V_G=sqrt(2/3)W+sqrt(1/3)R",
            "overlap": "W^T V_G=sqrt(2/3)I5",
            "retained_probability": "2/3",
            "path_energies": {"W": "2/3", "R": "5/3"},
            "residuals": {
                "overlap": overlap_error,
                "remainder_isometry": remainder_isometry_error,
                "remainder_orthogonality": remainder_orthogonality_error,
                "remainder_energy": remainder_energy_error,
            },
            "clock_and_charge_completion": {
                "native_return": {
                    "amplitude_matrix": (
                        "V_G^dag exp(-it H_path)V_G="
                        "[(2/3)exp(-2it/3)+(1/3)exp(-5it/3)]I5"
                    ),
                    "probability": "P_G(t)=(5+4cos(t))/9",
                    "relative_phase": "exp(-it)",
                    "probability_period": "2pi",
                    "spectral_weights": path_weights,
                    "other_spectral_weight": other_spectral_weight,
                    "samples": return_samples,
                },
                "logical_carry": {
                    "space": "span{W x,R x} for each logical x",
                    "path_hamiltonian": "diag(2/3,5/3)",
                    "path_invariance_residual": carry_path_residual,
                    "full_su5_closed": False,
                    "generator_leakage_range": [
                        min(generator_leakages),
                        max(generator_leakages),
                    ],
                },
                "charge_orbit": {
                    "exact_remainder_definition": exact_orbit["remainder_scale"],
                    "action": "Q(X)=X_1-X_2^T+X_3",
                    "rank_method": (
                        "exact algebraic rank of the 125 columns Q(E_ij)R_x; "
                        "these equal R plus the 24 traceless generator directions"
                    ),
                    "outer_symmetry_exact": exact_orbit["outer_symmetry_exact"],
                    "remainder_gram_exact": exact_orbit["remainder_gram_exact"],
                    "w_orthogonality_exact": exact_orbit["w_orthogonality_exact"],
                    "symmetric_sector_dimension": 75,
                    "remainder_orbit_rank": exact_orbit["orbit_rank"],
                    "w_plus_remainder_orbit_rank": exact_orbit["w_plus_orbit_rank"],
                    "representation_space": "Sym^2(5) tensor 5bar = 5 direct-sum 70",
                    "closure_reason": (
                        "the rank-70 orbit saturates the outer-symmetric "
                        "75-dimensional sector orthogonal to the invariant W five-space"
                    ),
                },
                "scope": (
                    "this is the existing finite H_path and collective SU(5) action: "
                    "the path phase supplies an exact internal carry clock, while "
                    "retaining arbitrary collective charge action requires the full "
                    "75-dimensional symmetric sector; it does not select a physical clock"
                ),
            },
        },
        "events": {
            "identity": "T_a^tensor3 W=WT_a",
            "count": 15,
            "maximum_residual": event_error,
        },
        "global_closure": {
            "local_identity": "Q_block^a W=W t_a for all 24 su(5) generators",
            "intertwiner_identity": (
                "H9 V=V(4I+h), hence exp(-it H9)V="
                "exp(-4it)V exp(-it h)"
            ),
            "projector_statement": (
                "every completed link commutes with each incident block projector"
            ),
            "finite_graph_statement": (
                "a sum of completed links on any finite graph preserves the full "
                "tensor product of W/Wbar block spaces exactly"
            ),
            "eliminated_block_corrections": (
                "zero within this completed model because PHQ=0 link by link"
            ),
            "covariance_residual": chain["covariance_error"],
            "scope": (
                "the nine-port collective completion is an additional rule forced "
                "by exact composition; the original marked A3 graph supplies one "
                "microscopic weak edge per coarse block pair, not all nine ports; "
                "invariance alone selects neither a global ground state nor a "
                "physical microscopic generator"
            ),
        },
        "coarse_a3": coarse,
        "sources": [
            {
                "path": "_newest2/TFPT_Gesamtdokumentation_20260927.md",
                "lines": "550-609",
                "claim": "quartic/event tensor G and its 60/40 decomposition",
            },
            {
                "path": "_newest2/TFPT_Gesamtdokumentation2_20260927.md",
                "lines": "1553-1693",
                "claim": "h_cov, W covariance, one-link projection, TL closure and generated words",
            },
            {
                "path": "tfpt_explorer/sources/TFPT_Konsolidierung_20260928.pdf",
                "pages": "42-44, 63-64",
                "claim": "marked A3 space, covariant trimer cover and harmonic periods",
            },
        ],
    }
    return {"data": data, "checks": checks}


__all__ = ["build_joint_data"]
